project_id = "eklkcgsbfpoogbmssvui"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_anonymous_sign_ins = false
enable_email_confirmations = false
enable_signup = true
enable_email_autoconfirm = false
enable_sms_autoconfirm = false
enable_manual_linking = false

[db]
enabled = true
port = 54322
major_version = 15

[edge_functions]
enabled = true
port = 54323
import_map = "./supabase/functions/import_map.json"

[functions.send-notification]
verify_jwt = false

[realtime]
enabled = true
port = 54324
max_concurrent_users = 200

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[analytics]
enabled = false
port = 54327
backend = "postgres"