// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eklkcgsbfpoogbmssvui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrbGtjZ3NiZnBvb2dibXNzdnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDE0NjgsImV4cCI6MjA2OTk3NzQ2OH0.TDz6xLDy77M8eIphty5KN4AT7E-8ujtnlrQKwQpdtM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});